### ISSUE TITLE
RecursionError: maximum recursion depth exceeded during compilation

### ISSUE THREAD

**Issue by PlawnWasSmart** [DevMeerkat/x-69-calculator#1]
First issue uwu https://discord.com/channels/504263175391412245/810877925041766400/885977135779577887
https://discord.com/channels/504263175391412245/810877925041766400/885187788859908127
![image](https://user-images.githubusercontent.com/67497065/132943430-913dfa01-3477-4522-8560-0b0b6c3701b8.png)

**Comment by DevMeerkat** [comment]
It's a feature, trust me bro
